### ISSUE TITLE
IANA Timezones broken

### ISSUE THREAD

**Issue by tgrelka** [jD91mZM2/TimeyWimey#1]
If you set your timezone to a IANA timezone (e.g. 'Europe/Berlin'), and and another user with a different timezone uses #timeat <yourtag>, it doesn't display the correct time, but one which is offset a few minutes.
Example:
<User1> #timezone Europe/Berlin (UTC+1)
<TimeyWimey>Set timezone "Europe/Berlin" for User1. Current time is 04:30PM
<User2> #timezone Europe/Stockholm (UTC+1)
<TimeyWimey> Set timezone "Europe/Stockholm" for User2. Current time is 04:30PM
<User2> #timeat 6PM @User1
<TimeyWimey> 6PM your time is 05:53PM for User1.
This shouldn't be 05:53, but also 06:00PM since both users are in the same timezone.
NOTE: It works fine when timezones are set using UTC tag.

**Comment by jD91mZM2** [comment]
We know. Please read README.md.
Also refer to [here](https://play.golang.org/p/_mnELD1nCv) for a code example on why.
